---
version: "3"

services:
  vault:
    image: vault:latest
    ports:
      - 8200:8200
    volumes:
      - .data:/vault/file
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_TOKEN: vault-root-token
      VAULT_DEV_ROOT_TOKEN_ID: vault-root-token
      BACKEND: file
    cap_add:
      - IPC_LOCK
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      PGDATA: /data
      POSTGRES_PASSWORD: "1"
    volumes:
      - .data:/data